[project]
name = "lesson-04-static-typing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas==2.3.3",
    "pydantic==2.12.5",
    "scikit-learn==1.8.0",
]

[dependency-groups]
dev = [
    "mypy==1.19.1",
    "pip-audit>=2.10.0",
    "ruff>=0.14.14",
]

[tool.mypy]
python_version = "3.11"
# Требует аннотации для всех функций
disallow_untyped_defs = true
# Предупреждает, если функция может вернуть Any
warn_return_any = true
# Игнорирует библиотеки без типов (например, старые или научные)
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pandas.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "sklearn.*"
ignore_missing_imports = true

[tool.ruff]
line-length = 80
indent-width = 4
output-format = "full"
target-version = "py311"

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "venv",
    "env",
    ".env",
    "__pypackages__",
    "_build",
    "buck-out",
    "dist",
    "node_modules",
]

src = [
    "app",
    "tests",
]

lint.select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    # "ANN",  # flake8-annotations
    "ASYNC",  # flake8-async
    "S",  # flake8-bandit
    "BLE",  # flake8-blind-except
    "A",  # flake8-builtins
    "COM",  # flake8-commas
    "C4",  # flake8-comprehensions
    "DTZ",  # flake8-datetimez
    "ISC",  # flake8-implicit-str-concat
    "G",  # flake8-logging-format
    "PIE",  # flake8-pie
    "T20",  # flake8-print
    "Q",  # flake8-quotes
    "SLF",  # flake8-self
    "SIM",  # flake8-simplify
    "ARG",  # flake8-unused-arguments
    "FLY",  # flynt
]
lint.ignore = [
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
    "S101",  # use of assert
    "G004",  # f-string in log messages
    "SIM105", # suppressible exceptions
    "COM812",  # выдает warning при форматировании кода
    "ISC001",   # выдает warning при форматировании кода
    "T201", # использования prin
    "C419", # использования list comprehension
]

extend-exclude = [
    "app/store/pg/migrations",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["ARG001", "ARG002"]
"config.py" = ["E501"]

